name: Deploy to S3 # CI/CD Pipeline
on:
  push:
    branches:
      - main  # adjust the branch name as needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      # - name: test build-Build and run dev container task
      #   uses: devcontainers/ci@v0.2
      #   with:
      #     python-version: 3.10

      - name: Checkout repository
        uses: actions/checkout@v3 # changed from 2

      # - name: Navigate to project directory
      #   run: cd ./lotto_actix

      - name : Check contents
        run: ls

      - name: Install dependencies
        run: make install

      - name: Format
        run: make format
      
      # - name: Linting
      #   run: make lint

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.S3_BUCKET_REGION }}

      
      - name : Scrape Arxiv
        env:
            API_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
            SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            ARXIV_REGION: us-east-1
            TARGET_REGION: ${{ secrets.S3_BUCKET_REGION }}
            BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run:
            python pdf_scraper.py

      
